version: '3.4'
networks:
  nx-net:
    external: false
services:
  nextcloud:
    image: arnofear/nextcloud-apache:12
    depends_on:
      - postgresql
    networks:
      - nx-net
    environment:
      - NEXTCLOUD_ADMIN_USER=nx_admin
      - NEXTCLOUD_ADMIN_PASSWORD=nx_pwd
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nx_user
      - POSTGRES_PASSWORD=nx_pwd
    volumes:
      - /var/docker/nextcloud/config:/var/www/html/config
      - /var/docker/nextcloud/custom_apps:/var/www/html/custom_apps
      - /var/docker/nextcloud/data:/var/www/html/data
      #- /var/docker/nextcloud/themes:/var/www/html/themes/<YOUR_CUSTOM_THEME>
    ports:
      - 80:80
  postgresql:
    image: arnofear/postgres-fr:9.6
    networks:
      - nx-net
    environment:
      - POSTGRES_PASSWORD=toto
    volumes:
      - /var/docker/postgresql/data:/var/lib/postgresql/data
    command: postgres -c log_timezone=Europe/Paris -c default_text_search_config=pg_catalog.french
